apiVersion: v1
kind: ConfigMap
metadata:
  name: go-food-config
  namespace: default
data:
  # DB Credentials (In production use K8s Secrets instead)
  POSTGRES_USER: "gofood"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "gofood_db"
  DATABASE_URL: "host=postgres user=gofood password=password dbname=gofood_db port=5432 sslmode=disable"
  MONGO_URI: "mongodb://mongo:27017"
  
  # API URLs (Internal Service Names)
  USER_SERVICE_URL: "http://user-service:8081"
  RESTAURANT_SERVICE_URL: "http://restaurant-service:8082"
  ORDER_SERVICE_URL: "http://order-service:8083"
  DELIVERY_SERVICE_URL: "http://delivery-service:8084"
  
  # Kafka Configs
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_ORDER_TOPIC: "orders"
  KAFKA_CONSUMER_GROUP: "delivery-service-group"
